### ISSUE TITLE
Did this can get the distance to the nearest edge of VD?

### ISSUE THREAD

**Issue by YaoQii** [GKIFreiburg/dynamic_voronoi#1]
hello,
       Given a point<x, y> in the 2D workspace, this code can get the distance to the nearest obstacle, but did it can get the distance to the nearest edge of the voronoi diagram?  

thanks

**Comment by aortlieb82** [comment]
Hey JohnQii,
unfortunately this package can not compute the distance to the nearest edge of the voronoi diagram.
The VD is not represented explicitly in the data structure, only the distances to the closest obstacles are stored.
Cheers
